In [2]:
import os
import ipyparallel as ipp

rc = ipp.Client()
ar = rc[:].apply_async(os.getpid)
pid_map = ar.get_dict()

In [3]:
print (pid_map)

{0: 137576, 1: 137584, 2: 137594, 3: 137603, 4: 137612, 5: 137628, 6: 137644, 7: 137660, 8: 137676, 9: 137692}


In [4]:
# Imports numpy on all workers
with rc[:].sync_imports():
    import numpy


importing numpy on engine(s)


In [5]:
# Runs the numpy command on all workers in parallel
%px a = numpy.random.rand(2,2)

In [6]:
%px print (a)

[stdout:0] 
[[0.71885701 0.06126652]
 [0.30710547 0.42692788]]
[stdout:1] 
[[0.90808758 0.10526718]
 [0.48471322 0.75031029]]
[stdout:2] 
[[0.82613825 0.68223569]
 [0.44037102 0.34223406]]
[stdout:3] 
[[0.78431795 0.07903946]
 [0.1922548  0.03219475]]
[stdout:4] 
[[0.6282042  0.88717304]
 [0.02241576 0.91790965]]
[stdout:5] 
[[0.86633801 0.70988761]
 [0.48736578 0.64169237]]
[stdout:6] 
[[0.27918113 0.34382915]
 [0.13012983 0.01365304]]
[stdout:7] 
[[0.93437622 0.57837283]
 [0.66729359 0.63954864]]
[stdout:8] 
[[0.84512551 0.57386426]
 [0.33118626 0.65376472]]
[stdout:9] 
[[0.19037971 0.82737999]
 [0.33484418 0.44597942]]


In [7]:
%px sum(a)

Out[0:3]: array([1.02596248, 0.4881944 ])

Out[1:3]: array([1.3928008 , 0.85557747])

Out[2:3]: array([1.26650928, 1.02446975])

Out[3:3]: array([0.97657274, 0.1112342 ])

Out[4:3]: array([0.65061996, 1.80508269])

Out[5:3]: array([1.35370379, 1.35157998])

Out[6:3]: array([0.40931096, 0.35748219])

Out[7:3]: array([1.60166981, 1.21792147])

Out[8:3]: array([1.17631177, 1.22762898])

Out[9:3]: array([0.5252239 , 1.27335941])

In [10]:
# Using the direct interface instead of %px magic
dview = rc[:]
parallel_result = dview.map_sync(lambda x: x**10, range(32))

In [9]:
print (parallel_result)

[0, 1, 1024, 59049, 1048576, 9765625, 60466176, 282475249, 1073741824, 3486784401, 10000000000, 25937424601, 61917364224, 137858491849, 289254654976, 576650390625, 1099511627776, 2015993900449, 3570467226624, 6131066257801, 10240000000000, 16679880978201, 26559922791424, 41426511213649, 63403380965376, 95367431640625, 141167095653376, 205891132094649, 296196766695424, 420707233300201, 590490000000000, 819628286980801]
