In [1]:
import os
import ipyparallel as ipp

rc = ipp.Client()
ar = rc[:].apply_async(os.getpid)
pid_map = ar.get_dict()

In [2]:
print (pid_map)

{0: 46735, 1: 46743, 2: 46752, 3: 46761, 4: 46770, 5: 46786, 6: 46802, 7: 46818, 8: 46835, 9: 46851}


In [9]:
# Imports numpy on all workers
with rc[:].sync_imports():
    import numpy


importing numpy on engine(s)


In [13]:
# Runs the numpy command on all workers in parallel
%px a = numpy.random.rand(2,2)

In [15]:
%px print (a)

[stdout:0] 
[[0.20237298 0.38307942]
 [0.70613644 0.08770603]]
[stdout:1] 
[[0.58618203 0.69179008]
 [0.08336017 0.36715467]]
[stdout:2] 
[[0.99506328 0.03451413]
 [0.71417828 0.51273679]]
[stdout:3] 
[[0.32670426 0.21691912]
 [0.93437067 0.37388136]]
[stdout:4] 
[[0.19922946 0.70604622]
 [0.22301556 0.25499656]]
[stdout:5] 
[[0.07976548 0.73881196]
 [0.90999392 0.01561677]]
[stdout:6] 
[[0.62862349 0.60812827]
 [0.58736609 0.78348685]]
[stdout:7] 
[[0.99958034 0.01716913]
 [0.23347221 0.65804518]]
[stdout:8] 
[[0.35327823 0.24312117]
 [0.21208876 0.62567883]]
[stdout:9] 
[[0.77905299 0.7570841 ]
 [0.69437286 0.61570489]]


In [16]:
%px sum(a)

Out[0:9]: array([0.90850942, 0.47078545])

Out[1:9]: array([0.6695422 , 1.05894475])

Out[2:9]: array([1.70924156, 0.54725092])

Out[3:9]: array([1.26107493, 0.59080047])

Out[4:9]: array([0.42224503, 0.96104278])

Out[5:9]: array([0.9897594 , 0.75442873])

Out[6:9]: array([1.21598958, 1.39161512])

Out[7:9]: array([1.23305255, 0.6752143 ])

Out[8:9]: array([0.565367, 0.8688  ])

Out[9:9]: array([1.47342585, 1.37278899])