In [10]:
%pip install ipyparallel

Note: you may need to restart the kernel to use updated packages.


In [1]:
# Start the workers run the below command in a separate terminal 
# ipcluster start -n 4 

In [ ]:
# Imports and setup a client for the parallel workers
import os
import ipyparallel as ipp

rc = ipp.Client()
ar = rc[:].apply_async(os.getpid)
pid_map = ar.get_dict()

In [3]:
print (pid_map)

{0: 2388, 1: 2389, 2: 2390, 3: 2392}


In [4]:
# Imports numpy on all workers
with rc[:].sync_imports():
    import numpy


importing numpy on engine(s)


In [5]:
# Runs the numpy command on all workers in parallel
%px a = numpy.random.rand(2,2)

In [6]:
%px print (a)

[stdout:0] 
[[0.78924898 0.67065159]
 [0.05240222 0.52415446]]
[stdout:1] 
[[0.35140494 0.88277812]
 [0.32626428 0.96795877]]
[stdout:2] 
[[0.40722583 0.41925194]
 [0.6581767  0.91964991]]
[stdout:3] 
[[0.96862513 0.9335422 ]
 [0.6563091  0.71454254]]


In [7]:
%px sum(a)

Out[0:3]: array([0.84165119, 1.19480605])

Out[1:3]: array([0.67766922, 1.85073689])

Out[2:3]: array([1.06540252, 1.33890186])

Out[3:3]: array([1.62493423, 1.64808474])

In [8]:
# Using the direct interface instead of %px magic
dview = rc[:]
parallel_result = dview.map_sync(lambda x: x**10, range(32))

In [9]:
print (parallel_result)

[0, 1, 1024, 59049, 1048576, 9765625, 60466176, 282475249, 1073741824, 3486784401, 10000000000, 25937424601, 61917364224, 137858491849, 289254654976, 576650390625, 1099511627776, 2015993900449, 3570467226624, 6131066257801, 10240000000000, 16679880978201, 26559922791424, 41426511213649, 63403380965376, 95367431640625, 141167095653376, 205891132094649, 296196766695424, 420707233300201, 590490000000000, 819628286980801]
